### ISSUE TITLE
Dll not being removed, HWID/KEY issue

### ISSUE THREAD

**Issue by KottenFAC** [Fenosk/DLL-Loader#1]
So i added the Dll link and it injects correct and it shows up but its not being removed from the C folder, i think it might be because its injected in "game" so it cant be removed, and also i added the key in a txt on a website but it says "wrong key or hwid" but when i removed hwid code its working so how do i fix that?

**Comment by dylanmit** [comment]
you need to CloseHandle(hFile) in manual_map, otherwise you won't be able to delete the dll till your program is closed.

**Comment by KottenFAC** [comment]
Am pretty sure its doing it...
![PNG](https://user-images.githubusercontent.com/46088757/78514128-0e888980-77b0-11ea-8a2d-143ee8abb79e.PNG)

**Comment by dylanmit** [comment]
in the manual_map function, somewhere after you call ReadFile(...)

**Comment by dylanmit** [comment]
> Am pretty sure its doing it... and if its not doing it how do i do it?
> ![PNG](https://user-images.githubusercontent.com/46088757/78514128-0e888980-77b0-11ea-8a2d-143ee8abb79e.PNG)

in the manual_map function, not FindProcessID, somewhere after you call ReadFile(...)

**Comment by KottenFAC** [comment]
Thanks alot dude it works :)

**Comment by Fenosk** [comment]
huh?

**Comment by KottenFAC** [comment]
the issue is fixed
